### PR TITLE
Enhanced Rdoc for Base64

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Revises introductory text and method descriptions.

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
Looks good, thanks for improving! 🎉

**Review by olleolleolle — APPROVED** [review]
I think this is ready!

**Comment by BurdetteLamar** [comment]
@mame, you are the maintainer here?  Can you (or someone) review?

**Comment by jcmfernandes** [comment]
I just wanted to stop by to say wow. Thank you, @BurdetteLamar. This is a fantastic piece of work :clap:.

**Comment by BurdetteLamar** [comment]
> I just wanted to stop by to say wow. Thank you, @BurdetteLamar. This is a fantastic piece of work 👏.

Thanks, @jcmfernandes.

**Pull request merged**
